[package]
name = "traash"
description = "traash, the Totally Radical And Awesome SHell"
version = "0.1.0"
authors = ["Astrid Yu <astrid@astrid.tech>"]
edition = "2018"

[build]
target = "li"

[dev-dependencies]
mockall = "0.9.0"

[dependencies]
nix = "0.19.1"
